events {}

http {

upstream task_backend {
    least_conn;
    server flask1:8000;
    server flask2:8000;
}

server {
    listen 80;
    return 301 https://$host$request_uri;
}

server {

    listen 443 ssl;

    ssl_certificate /etc/nginx/ssl/certs/server.crt;
    ssl_certificate_key /etc/nginx/ssl/certs/server.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {

        proxy_pass http://task_backend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /static/;
    }

}

}
